---
title: "PERE BLTB"
format:
  html:
    toc: true
    code-tools: true
---

# PERE BLTB / BLTB

:::: {.panel-tabset}

### Berom  
PERE BLTB  
BLTB we a Berom Language and Translation wogo, Tula e Lem na Doyo Takada Dagwi tanga jek Betakada e Lem Berom. Ba pere he e 1973 jende SIL (Summer Institute of Linguistic) ba nong Berom Nggwo Hanni Kuhn yi e Switzerland na a ra fwom jek Lem mot e gwong pwas gwo Jei, na be bin jek ke be doyo me Betakada. Jeng de ba hwo fwom o ba tanga doyo me TakadaDagwi, na jek Betakada behak.

### English  
INTRODUCTION  
BLTB is Berom Language and Translation Board, which means it's an organization concerning the Berom Language and Translation of the Bible and any other books in Berom Language. The organization began in 1973 when SIL (Summer Institute of Linguistic) assigned Ms Hanni Kuhn who came from Switzerland to work with the Berom in writing the Language in a modern way, to also write or translate books in the Language. When the work began they started with the translation of the Bible, followed with other literatures.

::::

